version: "3.8"

services:
  mautic:
    image: mautic/mautic:${VERSION:-v4}
    volumes:
      - mautic_data:/var/www/html
    networks:
      - traefik_public
      - app_network
    ports:
      - "8890:80" # Porta do Mautic URL 8890
    environment:
      # Banco de dados
      MAUTIC_DB_HOST: "mariadb"
      MAUTIC_DB_USER: "root"
      MAUTIC_DB_PASSWORD: "${SENHA_MARIADB}"
      MAUTIC_DB_NAME: "mautic"
      # Admin
      MAUTIC_URL: "https://${SUBDOMAIN}.${DOMAIN}"
      MAUTIC_ADMIN_EMAIL: "matheus@groufy.com.br"
      MAUTIC_ADMIN_PASSWORD: "${SENHA_MAUTIC}"
      # Configs da instalação
      MAUTIC_RUN_CRON_JOBS: "true"
      # MAUTIC_CRON_HUBSPOT: 
      PHP_INI_DATE_TIMEZONE: "America/Sao_Paulo"
      #MAUTIC_RUN_MIGRATIONS: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2'
          memory: 2048M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mautic.rule=Host(`${SUBDOMAIN}.${DOMAIN}`, `www.${SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.mautic.service=mautic"
        - "traefik.http.routers.mautic.entrypoints=websecure"
        - "traefik.http.routers.mautic.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.mautic.tls=true"
        - "traefik.http.services.mautic.loadbalancer.server.port=80"
 
volumes:
  mautic_data:

networks:
  traefik_public:
    external: true
  app_network:
    external: true