services:
  directus:
    image: directus/directus:${VERSION:-11.7.2}
    environment:
      # Secret Keys & Env
      - KEY=${SECRET_KEY_ENV}
      - SECRET=${SECRET_KEY_ENV}
      - APP_ENV=production
      - ADMIN_EMAIL=${SEU_EMAIL}
      - ADMIN_PASSWORD=${SUA_SENHA}
      - PUBLIC_URL=https://${SUBDOMAIN}.${DOMAIN}
      # Dados SMTP
      - EMAIL_TRANSPORT=smtp
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_IGNORE_TLS=${EMAIL_SMTP_IGNORE_TLS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE}
      - EMAIL_VERIFY_SETUP=${EMAIL_VERIFY_SETUP}

      # Dados MinIO
      - STORAGE_LOCATIONS=s3
      - STORAGE_S3_DRIVER=s3 
      - STORAGE_S3_KEY=${S3_ACCESS_KEY}
      - STORAGE_S3_SECRET=${S3_ACCESS_SECRET}
      - STORAGE_S3_BUCKET=directus
      - STORAGE_S3_REGION=us-east-1
      - STORAGE_S3_ENDPOINT=${S3_HOST}
      - STORAGE_S3_FORCE_PATH_STYLE=true

      # Redis
      - CACHE_ENABLED=false
      - CACHE_STORE=redis
      - CACHE_AUTO_PURGE=true
      - REDIS=redis://redis:6379/8

      # Dados Postgres
      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=directus
      - DB_USER=postgres
      - DB_PASSWORD=${SENHA_POSTGRES}
      
      # Cors
      - CORS_ENABLED=true
      - CORS_ORIGIN=true
      - CORS_METHODS=GET,POST,PATCH,DELETE
    volumes:
      - extensions:/directus/extensions
      - templates:/directus/templates
 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.directus.service: "directus"
        traefik.http.routers.directus.rule: "Host(`${SUBDOMAIN:-directus}.${DOMAIN:-seudominio.com.br}`, `www.${SUBDOMAIN:-directus}.${DOMAIN:-seudominio.com.br}`)"
        traefik.http.services.directus.loadbalancer.server.port: "8055"
        traefik.http.routers.directus.entrypoints: "websecure"
        traefik.http.routers.directus.tls.certresolver: "letsencryptresolver"
    networks:
      - externa
      - interna
volumes:
  extensions:
  templates:
  
networks:
  interna:
    external: true
  externa:
    external: true