version: "3.8"

services:
  typebot_builder:
    image: elestio/typebot-builder:v2.27.0
    networks:
      - externa
      - interna
    environment:
      #user:pass@hostname:porta/banco
      DATABASE_URL: postgresql://postgres:${SENHA_POSTGRES}@postgres:5432/typebot
      ENCRYPTION_SECRET: 2602ceb3ef3ced2646534d7ae073e87c
      NEXTAUTH_URL: https://${SUBDOMAIN}.${DOMAIN}
      NEXT_PUBLIC_VIEWER_URL: https://${SUBDOMAIN}.${DOMAIN}
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      #defina como "true" para desabilitar novos cadastros, faça isso depois de fazer o primeiro login
      DISABLE_SIGNUP: "false"
      #SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      #coloque dentro do sinal de maior e menor ex: <michel@gmail.com>
      #Infomome o mesmo valor utilizado da variavel SMTP_USERNAME
      NEXT_PUBLIC_SMTP_FROM: "Sua Empresa <${ADMIN_EMAIL}>"
      SMTP_PORT: 587
      SMTP_SECURE: "true"
      #Minio
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: typebot
      S3_ENDPOINT: ${S3_ENDPOINT}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.typebot_builder.rule=Host(`typebot.seudominio.com`)
        - traefik.http.routers.typebot_builder.tls.certresolver=le
        - traefik.http.routers.typebot_builder.entrypoints=websecure
        - traefik.http.routers.typebot_builder.tls=true
        - traefik.http.routers.typebot_builder.service=typebot_builder
        - traefik.http.services.typebot_builder.loadbalancer.server.port=3000

  typebot_viewer:
    image: elestio/typebot-viewer:v2.27.0
    networks:
      - externa
      - interna
    environment:
      #user:pass@hostname:porta/banco
      DATABASE_URL: postgresql://postgres:@postgres:5432/typebot
      ENCRYPTION_SECRET: 2602ceb3ef3ced2646534d7ae073e87c
      NEXTAUTH_URL: https://${SUBDOMAIN}.${DOMAIN}
      NEXT_PUBLIC_VIEWER_URL: https://${SUBDOMAIN}.${DOMAIN}
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      #defina como "true" para desabilitar novos cadastros, faça isso depois de fazer o primeiro login
      DISABLE_SIGNUP: "false"
      #SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      #coloque dentro do sinal de maior e menor ex: <michel@gmail.com>
      #Infomome o mesmo valor utilizado da variavel SMTP_USERNAME
      NEXT_PUBLIC_SMTP_FROM: "Sua Empresa <${ADMIN_EMAIL}>"
      SMTP_PORT: 587
      SMTP_SECURE: "true"
      #Minio
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: typebot
      S3_ENDPOINT: ${S3_ENDPOINT}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M
      labels:
        - traefik.enable=true
        #SSL
        - traefik.http.routers.typebot_viewer.rule=Host(`${SUBDOMAIN}.${DOMAIN}`, `www.${SUBDOMAIN}.${DOMAIN}`)
        - traefik.http.routers.typebot_viewer.tls.certresolver=letsencryptresolver
        - traefik.http.routers.typebot_viewer.entrypoints=websecure
        - traefik.http.routers.typebot_viewer.tls=true
        - traefik.http.routers.typebot_viewer.service=typebot_viewer
        - traefik.http.services.typebot_viewer.loadbalancer.server.port=3000
networks: 
  externa: 
    external: true
  interna: 
    external: true