x-variaveis: &variaveis
  # Configurações gerais do Chatwoot
  INSTALLATION_NAME: "${SUA_EMPRESA}"
  CHATWOOT_HUB_URL: "https://${SUBDOMAIN}.${DOMAIN}"
  NODE_ENV: ${NODE_ENV:-production}
  RAILS_ENV: ${RAILS_ENV:-production}
  INSTALLATION_ENV: docker
  
# Secret Key
  SECRET_KEY_BASE: ${SECRET_KEY_BASE:-"chave_hexadecimal_obrigatoria"}  # bundle exec rake secret
  
  # Configurações do Chatwoot
  FRONTEND_URL: "https://${SUBDOMAIN}.${DOMAIN}"
  DEFAULT_LOCALE: ${LANGUAGE:-pt_BR}
  FORCE_SSL: 'true'
  ENABLE_ACCOUNT_SIGNUP: 'false'
  USE_INBOX_AVATAR_FOR_BOT: 'true'

  # Serviços de armazenamento e logs
  REDIS_URL: redis://redis:6379
  ACTIVE_STORAGE_SERVICE: local
  RAILS_LOG_TO_STDOUT: 'true'

  # Configuração do banco de dados PostgreSQL
  POSTGRES_HOST: postgres
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: ${SENHA_POSTGRES:-"senha_do_postgres"}
  POSTGRES_DATABASE: chatwoot

  # Ajustes de performance
  SIDEKIQ_CONCURRENCY: '10'
  RACK_TIMEOUT_SERVICE_TIMEOUT: '0'
  RAILS_MAX_THREADS: '5'
  WEB_CONCURRENCY: '2'
  ENABLE_RACK_ATTACK: 'false'
  WEBHOOKS_TRIGGER_TIMEOUT: '40'

  # ChatGPT 
  # OPENAI_API_KEY: ${OPENAI:-sk-exampleopenaiapikey}

  # Servidor de Email Brevo
  MAILER_SENDER_EMAIL: "Chat - Zapefy <noreply@zapefy.com>"
  SMTP_DOMAIN: "smtp-brevo.com"
  SMTP_ADDRESS: "smtp-relay.brevo.com"
  SMTP_PORT: '587'
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  SMTP_ENABLE_STARTTLS_AUTO: 'true'
  SMTP_OPENSSL_VERIFY_MODE: 'peer'
  MAILER_INBOUND_EMAIL_DOMAIN: "noreply@zapefy.com"

  # Botão AUTH Google na tela de login
  # GOOGLE_OAUTH_CLIENT_ID: ${G_CLIENT_ID:-example.apps.googleusercontent.com}
  # GOOGLE_OAUTH_CLIENT_SECRET: ${G_LIENT_SECRET:-GOCSPX-example}
  # GOOGLE_OAUTH_CALLBACK_URL: ${G_CALLBACK_URL:-https://${SUBDOMAIN}.${DOMAIN}.com.br/omniauth/google_oauth2/callback}

services:
  chatwoot:
    image: chatwoot/chatwoot:v4.1.0
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    #command: >
    #  sh -c "bundle exec rails db:chatwoot_prepare &&
    #         bundle exec rails s -p 3000 -b 0.0.0.0 &&
    #         bundle exec rails db:migrate"
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - chatwoot_data:/app/storage
      - chatwoot_public:/app
      # Pasta com os arquivos do frontend (favicon, logo e outras)
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails
      - /root/custom/chatwoot_hub.rb:/app/lib/chatwoot_hub.rb
    networks:
      - externa
      - interna

    environment:
      <<: *variaveis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot.rule='Host(`${SUBDOMAIN}.${DOMAIN}`, `www.${SUBDOMAIN}.${DOMAIN}`)'
        - traefik.http.routers.chatwoot.entrypoints=web,websecure
        - traefik.http.routers.chatwoot.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot.priority=1
        - traefik.http.routers.chatwoot.service=chatwoot
        - traefik.http.services.chatwoot.loadbalancer.server.port=3000
        - traefik.http.services.chatwoot.loadbalancer.passhostheader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot.middlewares=sslheader@docker

  chatwoot_worker:
    image: chatwoot/chatwoot:v4.1.0
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_data:/app/storage
      - chatwoot_public:/app
      # Pasta com os arquivos do frontend (favicon, logo e outras)
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails
      - /root/custom/chatwoot_hub.rb:/app/lib/chatwoot_hub.rb
    networks:
      - externa
      - interna
    environment:
      <<: *variaveis
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 2048M

volumes:
  chatwoot_data:
    external: true
    name: chatwoot_data
  chatwoot_public:
    external: true
    name: chatwoot_public
  chatwoot_mailer:
    external: true
    name: chatwoot_mailer
  chatwoot_mailers:
    external: true
    name: chatwoot_mailers

networks: 
  externa: 
    external: true
    name: externa
  interna: 
    external: true
    name: interna